config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'dashboard#index'
  
  namespace :references do
    resources :clients do 
      get 'select_clients_dialog', on: :collection
    end  
    resources :users
    resources :stock_locations
    resources :brands
    resources :models do 
      get 'select_models_dialog', on: :collection
    end
    resources :equipment_types  
  end
  
  namespace :documents do
    resources :orders
    resources :order_transfers, only: %w(new create)
  end  
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM
  acts_as_paranoid
  
  paginates_per 20
  
  aasm column: 'work_status' do
    state :accepted, initial: true
    state :transferred_to_engineer
    state :received_from_the_engineer
    state :diagnosed
    
    event :transfer do
      transitions from: %w(accepted received_from_the_engineer), to: :transferred_to_engineer, if: :order_moved_to_engineer?
      transitions from: :transferred_to_engineer, to: :received_from_the_engineer, unless: :order_moved_to_engineer?
    end
  end

  #aasm column: 'payment_status' do
  #  state :not_paid, initial: true
  #  state :partially_paid
  #  state :fully_paid
  #end
    
  belongs_to :model
  belongs_to :client
  belongs_to :user
  belongs_to :stock_location
  belongs_to :current_stock_location, class_name: 'StockLocation'
  
  has_many :status_changes, class_name: 'OrderStatusChange'
  has_many :transfers, class_name: 'OrderTransfer'
  
  after_create :set_current_stock_location, :create_status_change
  
  # job types
  PAY_TYPE = 0
  GARANTY_TYPE = 1
  
  scope :ordered, -> {order('created_at DESC')}
  
  def type
    job_type.zero? ? 'Платный' : 'Гарантийный'
  end
  
  def equipment_type_title
     model.equipment_type.present? ? model.equipment_type.title : ''
  end
  
  def brand_title
    model.brand.present? ? model.brand.title : ''
  end
  
  def model_title
    model.present? ? model.title : ''
  end
  
  def client_name
    client.name
  end
  
  def working_state
    case work_status
    when "accepted"
      'Принято'
    when 'transferred_to_engineer'
      'Передано инженеру'
    when 'diagnosed'
      'Диагностировано'
    when 'received_from_the_engineer'
      'Получено от инженера'  
    else 
      '-'
    end        
  end
  
  def working_state_color
    case work_status
    when 'accepted'
      '#FF734C'
    when 'transferred_to_engineer'
      '#FFAF48'
    when 'diagnosed'
      '#FFF4C0'
    when 'received_from_the_engineer'
      '#E07DE0'
    else 
      '#fff'
    end        
  end      
  
  def self.search(search)
    if search
      joins(:model, :client).where('LOWER(models.title) LIKE ? OR CAST(orders.id AS text) LIKE ? OR LOWER(clients.name) LIKE ?', "%#{search.downcase}%", "%#{search}%", "%#{search.downcase}%")
    else
      includes(:model, :client).all
    end
  end 
  
  private
  
  def order_moved_to_engineer?
    current_stock_location.is_engineer_stock  
  end 
  
  def set_current_stock_location
    self.update_attribute(:current_stock_location, stock_location)
  end
  
  def create_status_change
    status_changes.create(status: work_status, originator: self)
  end    
end

app/controllers/documents/order_transfers_controller.rb
class Documents::OrderTransfersController < ApplicationController
  before_action :set_order, only: %w(new create)

  def index
    respond_to do |format|
      format.html
      format.js {render layout: false}
    end 
  end

  def new
    @order_transfer = @order.transfers.build
    render layout: false
  end

  def create
    @order_transfer = @order.transfers.build(order_transfer_params)

    respond_to do |format|
      if @order_transfer.save
        format.html { redirect_to documents_orders_url, notice: 'Заказ наряд успешно перемещён.' }
        format.json { render :show, status: :created, location: @order_transfer }
      else
        format.html { render :new }
        format.json { render json: @order_transfer.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  private
    def set_order
      @order = Order.find params[:order_id]
    end  
    
    def order_transfer_params
      params.require(:order_transfer).permit(:order_id, 
                                             :source_location_id, 
                                             :destination_location_id, 
                                             :description,
                                             :user_id)
    end
end

app/controllers/documents/orders_controller.rb
class Documents::OrdersController < ApplicationController
  before_action :set_order, only: %w(show edit update destroy)

  def index
    respond_to do |format|
      format.html { @orders_total_number = Order.count } 
      format.json { render text: Order.search(params[:search]).
                                 ordered.
                                 page(params[:page]).
                                 to_json(methods: [:brand_title, :model_title, 
                                                   :client_name, :type, 
                                                   :equipment_type_title, 
                                                   :working_state, 
                                                   :working_state_color
                                                  ]
                                        )
                  }
      format.js {render layout: false}
    end
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to documents_orders_url, notice: 'Заказ наряд успешно создан.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to documents_orders_url, notice: 'Заказ наряд успешно изменён.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to documents_orders_url, notice: 'Заказ наряд успешно удалён.' }
      format.json { head :no_content }
    end
  end
  
  
  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:client_id, :user_id, :stock_location_id, 
                                    :job_type, :model_id, :imei, :serial_number,
                                    :defect, :completeness, :appearance, :description)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def job_types
    [['Платный', Order::PAY_TYPE], ['Гарантийный', Order::GARANTY_TYPE]]
  end
  
    
  def order_action_links(order)
    [content_tag(:li, link_to('Смотреть', documents_order_path(order))),
     content_tag(:li, link_to('Редактировать', edit_documents_order_path(order))),
     content_tag(:li, link_to('Удалить', 
                              documents_order_path(order), 
                              method: :delete, 
                              data: { confirm: "Вы действительно хотите удалить заказ?" })),
     content_tag(:li, link_to('Переместить', 
                              new_documents_order_transfer_path(order_id: order),
                              data: {target: "#modalDialog", 
                                     toggle: "modal", 
                                     remote: false, 
                                     title: 'Перемещение'}))    
    ].join.html_safe
         
  end       
end

app/views/documents/orders/_form.slim
= form_for(@order, url: @order.new_record? ? documents_orders_path : documents_order_path(@order)) do |f|
  = error_messages(@order)
  .row 
    = f.hidden_field :user_id, value: current_user.id
    .form-group.col-md-6
      = f.label :stock_location_id
      = f.select :stock_location_id, StockLocation.all.map{ |w| [w.name, w.id]}, {}, {class: 'form-control'}
    .form-group.col-md-6
      = f.label :job_type
      = f.select :job_type, job_types, {}, {class: 'form-control'}
  .row      
    .form-group.col-md-6
      = f.label :client_id
      .input-group
        = text_field_tag :client_name, @order.client.try(:name), class: 'form-control', disabled: true 
        .input-group-addon
          = link_to select_clients_dialog_references_clients_path, data: {target: "#modalDialog", toggle: "modal", remote: false, title: 'Контрагенты', search_action: select_clients_dialog_references_clients_path, new_link: new_references_client_path} do 
            i.fa.fa-search
        = f.hidden_field :client_id, class: 'form-control'      
    .form-group.col-md-6
      = f.label :model_id
      .input-group
        = text_field_tag :model_title,  @order.model.try(:title_with_brand), class: 'form-control', disabled: true
        .input-group-addon
          = link_to select_models_dialog_references_models_path, data: {target: "#modalDialog", toggle: "modal", remote: false, title: 'Модели', search_action: select_models_dialog_references_models_path, new_link: new_references_model_path} do 
            i.fa.fa-search
        = f.hidden_field :model_id, class: 'form-control'      
  .row
    .form-group.col-md-6
      = f.label :imei
      = f.text_field :imei, class: 'form-control'
    .form-group.col-md-6
      = f.label :serial_number
      = f.text_field :serial_number, class: 'form-control'          
  .form-group
    = f.label :defect
    = f.text_field :defect, class: 'form-control'
  .form-group
    = f.label :completeness
    = f.text_field :completeness, class: 'form-control'
  .form-group
    = f.label :appearance
    = f.text_field :appearance, class: 'form-control'              
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'   
  .box-footer
    = link_to t('app.buttons.back'), :back, class: 'btn btn-default'
    = f.submit (@order.new_record? ? 'Создать' : 'Изменить'), class: "btn btn-info pull-right" 

app/views/documents/orders/_navigation.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Заказ наряды', documents_orders_path, class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li= link_to 'Новый заказ наряд', new_documents_order_path

app/views/documents/orders/_orders.slim
- orders.each do |order|
  tr[style="background-color: #{order_status_color(order)}"]
    td= render 'shared/table_actions', actions: order_action_links(order)
    td= l(order.created_at, format: :default)  
    td= order.id  
    td= order.model.brand.title
    td= order.model.title
    td= order.client.name
    td= order.type
    td= order.completeness
    td= order_work_status(order)

app/views/documents/orders/_transfers.slim
table.table.table-bordered
  tr
    th Дата
    th Документ
    th Отправитель
    th Получатель
    th Ответственный
  tr
    td= l @order.created_at 
    td= "Заказ наряд № #{@order.id}"
    td= @order.client.name 
    td= @order.stock_location.name
    td= @order.user.full_name
  - @order.transfers.ordered.each do |transfer|
    tr
      td= l transfer.created_at
      td= "Перемещение № #{transfer.id}"
      td= transfer.source_location.name
      td= transfer.destination_location.name
      td= @order.user.full_name

app/views/documents/orders/edit.slim
- page_title 'Изменить заказ наряд'

.col-md-6
  = render 'form'

app/views/documents/orders/index.js.erb
$(".infinite-table table").append("<%= j render(partial: 'orders', locals: {orders: @orders}) %>");
<% if @orders.last_page? %>
  $('.pagination').html("Конец");
<% else %>
  $('.pagination').html("<%= j link_to_next_page(@orders, 'Следующие', remote: true) %>");
<% end %>

app/views/documents/orders/index.slim
.row ng-controller='ordersController' ng-init='init("#{@orders_total_number}")'
  .col-md-12
    .box
      = render 'navigation'
      .box-body.table-container
        table.table.table-hover[st-table='displayedOrders' st-safe-src='orders' st-pagination-scroll st-pipe='callServer']
          thead
            tr
              th[style='width: 30px;']
              th Дата
              th Номер
              th Вид оборудования
              th Брэнд
              th Модель
              th Контрагент
              th Тип работы
              th Комплектность
              th Статус
            tr
              th colspan="10"
                input.form-control[st-search="search" placeholder="Поиск ..." type="search"]
          tbody 
            tr style="background-color: {{order.working_state_color}}" ng-repeat='order in displayedOrders'
              td
                .dropdown
                  button.btn.btn-default.btn-xs[id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
                    span.caret
                  ul.dropdown-menu[aria-labelledby="dLabel"]
                    li
                      a[href="/documents/orders/{{order.id}}"] Смотреть
                    li
                      a[href="/documents/orders/{{order.id}}/edit"] Редактировать
                    li
                      a[href="/documents/order_transfers/new?order_id={{order.id}}" data-target="#modalDialog" data-toggle="modal" data-remote="false" data-title="Перемещение"] Переместить     
              td 
                | {{order.created_at | date}}
              td 
                | {{order.id}}
              td 
                | {{order.equipment_type_title}} 
              td 
                | {{order.brand_title}}
              td 
                | {{order.model_title}}
              td 
                | {{order.client_name}}
              td
                | {{order.type}}  
              td
                | {{order.completeness}}
              td
                | {{order.working_state}}          
      .loading-indicator ng-show="isLoading"

app/views/documents/orders/new.slim
- page_title 'Новый заказ наряд'

.col-md-6
  = render 'form'

app/views/documents/orders/show.slim
- page_title ["Заказ наряд №", @order.id].join(' ')

section.show.invoice
  .row
    .col-md-12
      .panel-group#accordion[role="tablist" aria-multiselectable="true"]
        .panel.panel-default
          .panel-heading[role="tab"]
            h4.panel-title
              a role="button" data-toggle="collapse" data-parent="#accordion" href="#commonData" aria-expanded="true" aria-controls="commonData"
                | Общие данные по заказ наряду 

          #commonData.panel-collapse.collapse[role="tabpanel" aria-labelledby="commonData"]
            .panel-body
              dl
                dt Тип работы
                dd= @order.type
                dt Заявленный дефект
                dd= @order.defect
                dt Комплектность
                dd= @order.completeness
                dt Внешний вид
                dd= @order.appearance
                dt Комментарий
                dd= @order.description
      
        .panel.panel-default
          .panel-heading[role="tab"]
            h4.panel-title
              a role="button" data-toggle="collapse" data-parent="#accordion" href="#client" aria-expanded="true" aria-controls="client"
                | Контрагент: 
                span= @order.client.name

          #client.panel-collapse.collapse[role="tabpanel" aria-labelledby="client"]
            .panel-body
              dl
                dt Адрес
                dd= @order.client.address
                dt Телефон
                dd= [@order.client.phone, @order.client.additional_phone].join(' ')

        .panel.panel-default
          .panel-heading[role="tab"]
            h4.panel-title
              a role="button" data-toggle="collapse" data-parent="#accordion" href="#model" aria-expanded="true" aria-controls="model"
                | Модель: 
                span= @order.model.title_with_brand

          #model.panel-collapse.collapse[role="tabpanel" aria-labelledby="model"]
            .panel-body
              dl
                dt IMEI
                dd= @order.imei
                dt Серийный номер
                dd= @order.serial_number
        
        .panel.panel-default
          .panel-heading[role="tab"]
            h4.panel-title
              a role="button" data-toggle="collapse" data-parent="#accordion" href="#currentLocation" aria-expanded="true" aria-controls="currentLocation"
                | Текущее местонахождение: 
                span= @order.current_stock_location.name 

          #currentLocation.panel-collapse.collapse[role="tabpanel" aria-labelledby="currentLocation"]
            .panel-body
              = render 'transfers'
                       
                
        .panel.panel-default
          .panel-heading[role="tab"]
            h4.panel-title
              a role="button" data-toggle="collapse" data-parent="#accordion" href="#additionalInfo" aria-expanded="true" aria-controls="additionalInfo"
                | Дополнительная информация: 

          #additionalInfo.panel-collapse.collapse[role="tabpanel" aria-labelledby="additionalInfo"]
            .panel-body
              dl
                dt Принято на склад
                dd= @order.stock_location.name
                dt Ответственный
                dd= @order.user.full_name  

  .row.actions
    .col-xs-12
      = link_to 'Назад', :back, class: "btn btn-default"
      = link_to edit_documents_order_path(@order), class: "btn btn-primary pull-right" do
        <i class="fa fa-edit"></i> Изменить
      = link_to "#", class: "btn btn-success pull-right", style: "margin-right: 5px;" do
        <i class="fa fa-print"></i> Печать    