config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'dashboard#index'
  
  namespace :references do
    resources :clients do 
      get 'select_clients_dialog', on: :collection
    end  
    resources :users
    resources :stock_locations
    resources :brands
    resources :models do 
      get 'select_models_dialog', on: :collection
    end
    resources :equipment_types  
  end
  
  namespace :documents do
    resources :orders
    resources :order_transfers, only: %w(new create)
  end  
end

app/views/shared/_flash_messages.slim
.row.alert-box
  .col-md-12
    - flash.each do |type, content|
      - case type
      - when "alert"
        - div_class = "bg-danger"
      - when "notice"
        - div_class = "bg-warning"
      - when "success"
        - div_class = "bg-success"
      - if content.is_a?(String)
        .alert.fade.in class=div_class
          button.close data-dismiss="alert" type="button"
            span aria-hidden="true" ×
            span.sr-only Close
          = content

app/views/shared/_header.html.slim
header.main-header
  = link_to root_path, class: 'logo' do 
    span.logo-mini
      b
        | C
      | SC
    span.logo-lg
      b
        | Admin
      | CSC
  nav.navbar.navbar-static-top
    a.sidebar-toggle[href="#" data-toggle="offcanvas" role="button"]
      span.sr-only
        | Toggle navigation
    .navbar-custom-menu
      ul.nav.navbar-nav
        li.dropdown.user.user-menu
          a.dropdown-toggle[href="#" data-toggle="dropdown"]
            = image_tag 'no-user-image.png', class: 'user-image'
            span.hidden-xs= current_user.full_name 
          ul.dropdown-menu
            li.user-header
              = image_tag 'no-user-image.png', class: 'img-circle'
              p= current_user.full_name
            li.user-footer
              .pull-left
                = link_to t('app.navigation.user.profile'), edit_user_registration_path, class: 'btn btn-default btn-flat'
              .pull-right
                = link_to t('app.navigation.user.sign_out'), destroy_user_session_path, class: 'btn btn-default btn-flat'

app/views/shared/_modal_dialog.slim
#modalDialog.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close[type="button" data-dismiss="modal" aria-hidden="true"]
          | ×
        h4.modal-title
        div.search-form  
          = form_tag("#", remote: true, method: 'get', id: 'searchForm') do
            .form-group
                = text_field_tag :search, nil, autofocus: true, class: 'form-control'
      .modal-body#listContainer    
      .modal-footer 
        = link_to 'Новый', "#", remote: true, class: 'btn btn-default pull-left', id: 'newLink'
        button.btn.btn-default[type="button" data-dismiss="modal"]
          | Закрыть
        button.btn.btn-primary#submitDialogBtn
          | Применить

app/views/shared/_sidebar.html.slim
aside.main-sidebar
  section.sidebar
    .user-panel
      .pull-left.image
        = image_tag 'no-user-image.png', class: 'img-circle'
      .pull-left.info
        p= current_user.full_name
        /a[href="#"]
        /  i.fa.fa-circle.text-success
        /  |  Online
    ul.sidebar-menu
      li.header
        | МЕНЮ
      li.treeview class=(params[:controller].include?('references') ? 'active' : '')
        a[href="#"]
          i.fa.fa-book
          span= t('app.navigation.menu.references')
          span.pull-right-container
            i.fa.fa-angle-left.pull-right 
        ul.treeview-menu
          li
            = active_link_to references_users_path, wrap_tag: :li do
              i.fa.fa-circle-o
              = t 'app.navigation.menu.users'  
          li
            = active_link_to references_stock_locations_path, wrap_tag: :li do
              i.fa.fa-circle-o
              | Склады
          li
            = active_link_to references_equipment_types_path, wrap_tag: :li do
              i.fa.fa-circle-o
              | Типы оборудования     
          li
            = active_link_to references_brands_path, wrap_tag: :li do
              i.fa.fa-circle-o
              | Брэнды 
          li
            = active_link_to references_models_path, wrap_tag: :li do
              i.fa.fa-circle-o
              | Модели
          li
            = active_link_to references_clients_path, wrap_tag: :li do
              i.fa.fa-circle-o
              | Клиенты 

        li.treeview class=(params[:controller].include?('documents') ? 'active' : '')
          a[href="#"]
            i.fa.fa-book
            span Документы
            span.pull-right-container
              i.fa.fa-angle-left.pull-right 
          ul.treeview-menu
            li
              = active_link_to documents_orders_path, wrap_tag: :li do
                i.fa.fa-circle-o
                | Заказ наряды
                
        li.treeview
          a[href="#"]
            i.fa.fa-book
            span Отчёты
            span.pull-right-container
              i.fa.fa-angle-left.pull-right                                  

app/views/shared/_table_actions.slim
.dropdown
  button.btn.btn-default.btn-xs[id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
    span.caret
  ul.dropdown-menu[aria-labelledby="dLabel"]
    = actions